# Basic options
title: Coding For Reproducible Research
short_name: Coding For Reproducible Research
description: University of Exeter programme to develop programming expertise  


# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
    sort_by: lesson

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
      layout: page
  - scope:
      path: ""
      type: episodes
    values:
      root: ..
      layout: episode
  - scope:
      path: ""
      type: extras
    values:
      root: ..
      layout: page

# Build settings
theme: jekyll-theme-slate
